version: '3.8'

networks:
    net_service:
        external:
            name: net_service

services:
    apache:
        image: 25watts/magento:1.9.4
        ports:
            - 85:80 # web
        volumes:
            - .:/var/www/html
        networks:
            - net_service