version: '3.8'

networks:
    net_mysql:
        external:
            name: NetMysql
    net_redis:
        external:
            name: NetRedis
    net_mail:
        external:
            name: NetMailHog
    net_elasticsearch:
        external:
            name: NetElasticsearch
services:
    apache:
        image: 25watts/magento:2.4
        ports:
            - 85:80
            - 443:443
        volumes:
            - apache-sync-jmc:/var/www/html:nocopy,delegated
        networks:
            - net_mysql
            - net_redis
            - net_mail
            - net_elasticsearch

volumes:
  apache-sync-jmc:
    external: true