version: '3.8'

networks:
    net_service:
        external:
            name: net_service

services:
    apache:
        image: 25watts/wordpress:5.4
        ports:
            - 85:80
        volumes:
            - .:/var/www/html
        networks:
            - net_service