#!/usr/bin/env bash

COMPOSE="docker-compose -f docker-compose.yml"

if [ $# -gt 0 ]; then
    if [ "$1" = "up" ]; then
        shift 1
        $COMPOSE up "$@" -d

        mutagen sync terminate --label-selector "magento2"
        mutagen sync create -c mutagen.yml \
            --label="magento2" \
            $(pwd) docker://www-data@$(docker-compose ps -q apache)/var/www/html
    elif [ "$1" = "stop" ]; then
        $COMPOSE stop
        mutagen sync pause --label-selector "magento2"
    elif [ "$1" = "down" ]; then
        $COMPOSE down --remove-orphans
        mutagen sync terminate --label-selector "magento2"
    fi
fi
