version: '3.8'

networks:
    net_mysql:
        external:
            name: NetMysql
    net_redis:
        external:
            name: NetRedis
services:
    apache:
        image: 25watts/magento2:2.1
        # build: .
        ports:
            - 85:80
            - 443:443
        volumes:
            # - .:/var/www/html:cached
            - apache-sync:/var/www/html:nocopy,delegated
            - ~/.composer:/var/www/.composer
            - ~/.npm:/var/www/.npm
        # environment:
            # PHP_IDE_CONFIG: "serverName=Docker"
        networks:
            - net_mysql
            - net_redis

volumes:
  apache-sync:
    external: true