version: '3.8'

networks:
    net_mysql:
        external:
            name: NetMysql
services:
    apache:
        image: 25watts/php:5.6
        ports:
            - 85:80
        volumes:
            - .:/var/www/html
            - ~/.composer:/var/www/.composer
            - ~/.npm:/var/www/.npm
        networks:
            - net_mysql
