version: '3.8'

networks:
    net_service:
        external:
            name: net_service

services:
    apache:
        image: 25watts/magento2:2.3
        ports:
            - 86:80
            - 443:443
        volumes:
            - .:/var/www/html:cached
            - ~/.composer:/var/www/.composer
            - ~/.npm:/var/www/.npm
        networks:
            - net_service
