version: '3.8'

networks:
    net_mysql:
        external:
            name: NetMysql

services:
    apache:
        image: 25watts/magento:1.9
        ports:
            - 85:80 # web
        volumes:
            - .:/var/www/html
        networks:
            - net_mysql