version: '3.8'

networks:
    net_service:
        external:
            name: net_service

services:
    apache:
        image: 25watts/php:7.2
        ports:
            - 85:80 # web
        volumes:
            - .:/var/www/html
            - ~/.composer:/var/www/.composer
        networks:
            - net_service