version: '3.7'

networks:
    net_elasticsearch:
        name: NetElasticsearch

services:
  elasticsearch:
    image: elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - net_elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - net_elasticsearch
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local