version: "3.3"

networks:
    net_service:
        name: net_service

services:
    traefik:
        image: "traefik:v2.4"
        container_name: "traefik"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - ./traefik.toml:/traefik.toml
            - ./traefik_dynamic.toml:/traefik_dynamic.toml
            - ./acme.json:/acme.json
        networks:
            - net_service

    whoami:
        image: "traefik/whoami"
        container_name: "simple-service"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`test.localhost`)"
            - "traefik.http.routers.whoami.entrypoints=websecure"
            - "traefik.http.routers.whoami.tls=true"
            - "traefik.http.routers.whoami.tls.certresolver=lets-encrypt"
            - "traefik.port=80"
        networks:
            - net_service