[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$ajDlJyq9$TwzT7wEbadZ3scnaF31rQ0"
  ]

[http.routers.api]
  rule = "Host(`traefik.localhost`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"